### PR TITLE
Duplicate fix on /movie endpoint

### LINKED ISSUE #12: Handle duplicates in the /movie endpoint
Right now when you search `/movie/titanic` there is 2 entries, one from 1953

https://github.com/zedchance/oscars/blob/dd54afd80c269ce2d418d22ee87caabce4a6b36d/src/main/CSVFile/KaggleData_the_oscar_award.csv#L2782

and one from 1997

https://github.com/zedchance/oscars/blob/dd54afd80c269ce2d418d22ee87caabce4a6b36d/src/main/CSVFile/KaggleData_the_oscar_award.csv#L7684

We should figure out a way to handle when the user wants a instance response, but there are multiple movies by that title.

### PR DESCRIPTION
**Pull request by zedchance**
Okay so the `/movie` endpoint will always return the oldest movie, if duplicate titles exist. To be able to get the specific title from a certain year the `year` option can be specified. (#12)

For example:

```
localhost:8080/movie/titanic
```

will return the 1953 version, and

```
localhost:8080/movie/titanic?year=1997
```

will return the 1997 version.

This keeps the `/movie` endpoint as a singleton resource, while allowing the ability to get the others when a title is duplicated.

Also: Updated DELIVERABLES with a link to the unit tests and mockups. Updated the wiki to clarify what happens when duplicates exist and how to use the `year` option.

### CODE REVIEW

File: src/main/java/api/Controller.java [hunk 1]
```diff
@@ -37,24 +37,45 @@ public Hello hello(@RequestParam(value = "name", defaultValue = "team3") String
     }
 
     /**
-     * An endpoint that returns a specific movie
+     * An endpoint that returns a specific movie. If two movies share the same title,
+     * the oldest is returned. To get a specific movie of a certain year, add the
+     * year paramter, i.e. /movie/titanic?year=1997
```
Comment (vgalbraith) [inline src/main/java/api/Controller.java:42]: Mistyped parameter in the comment here. The rest looks good!

**Review by vgalbraith — APPROVED** [review]

File: src/main/java/api/Controller.java (hunk 1 above)
Comment (zedchance) [reply src/main/java/api/Controller.java:42]: I saw that, in the commit message too 👎
